import type { RuntimeCharacter } from './runtimeTypes';

export const seedCharacter: RuntimeCharacter = {
  id: 'Q9036',
  name: 'Nikola Tesla',
  rarity: 'S',
  source: {
    wikidata_id: 'Q9036',
    wikidata_url: 'https://www.wikidata.org/wiki/Q9036',
    wikipedia_title: 'Nikola Tesla',
    wikipedia_url: 'https://en.wikipedia.org/wiki/Nikola_Tesla',
    language: 'en',
  },
  stats: {
    hp: 55,
    attack: 50,
    defense: 50,
    speed: 50,
    intelligence: 75,
    influence: 50,
    survival: 50,
  },
  tags: ['science', 'scholar', 'technology'],
  lore: 'Nikola Tesla was an inventor and electrical engineer whose work inspires technology-focused combat cards.',
  short_lore: 'Inventor and electrical engineer.',
  cards: [
    {
      id: 'tesla_coil',
      owner_character_id: 'nikola_tesla',
      name: 'Tesla Coil',
      card_type: 'attack',
      card_rarity: 'basic',
      energy_cost: 1,
      description: 'Unleash a high-voltage shock that arcs to the front enemy.',
      mechanics_text: 'Deal 8 damage to front enemy.',
      mechanics: [
        {
          kind: 'damage',
          target: 'front_enemy',
          amount: { base: 8, scaling_stat: 'none', scaling_ratio: 0 },
          status: null,
          duration: null,
          condition: null,
        },
      ],
      targeting: null,
      exhaust: false,
      upgraded: false,
    },
    {
      id: 'alternating_current',
      owner_character_id: 'nikola_tesla',
      name: 'Alternating Current',
      card_type: 'skill',
      card_rarity: 'common',
      energy_cost: 2,
      description: 'Send a surge of alternating current that bounces between enemies.',
      mechanics_text: 'Deal 5 damage to all enemies.',
      mechanics: [
        {
          kind: 'damage',
          target: 'all_enemies',
          amount: { base: 5, scaling_stat: 'none', scaling_ratio: 0 },
          status: null,
          duration: null,
          condition: null,
        },
      ],
      targeting: null,
      exhaust: false,
      upgraded: false,
    },
    {
      id: 'wireless_transmission',
      owner_character_id: 'nikola_tesla',
      name: 'Wireless Transmission',
      card_type: 'utility',
      card_rarity: 'common',
      energy_cost: 1,
      description: 'Harness wireless energy to shield an ally.',
      mechanics_text: 'Grant 10 shield to selected ally.',
      mechanics: [
        {
          kind: 'shield',
          target: 'selected_ally',
          amount: { base: 10, scaling_stat: 'none', scaling_ratio: 0 },
          status: null,
          duration: null,
          condition: null,
        },
      ],
      targeting: null,
      exhaust: false,
      upgraded: false,
    },
    {
      id: 'magnifying_transmitter',
      owner_character_id: 'nikola_tesla',
      name: 'Magnifying Transmitter',
      card_type: 'power',
      card_rarity: 'rare',
      energy_cost: 2,
      description: 'Amplify your energy output, drawing extra cards.',
      mechanics_text: 'Draw 2 cards.',
      mechanics: [
        {
          kind: 'draw_cards',
          target: 'self',
          amount: { base: 2, scaling_stat: 'none', scaling_ratio: 0 },
          status: null,
          duration: null,
          condition: null,
        },
      ],
      targeting: null,
      exhaust: false,
      upgraded: false,
    },
    {
      id: 'wardenclyffe_tower',
      owner_character_id: 'nikola_tesla',
      name: 'Wardenclyffe Tower',
      card_type: 'ultimate',
      card_rarity: 'ultimate',
      energy_cost: 3,
      description: 'Channel the full power of the Wardenclyffe Tower to devastate all foes.',
      mechanics_text: 'Deal 20 damage to all enemies.',
      mechanics: [
        {
          kind: 'damage',
          target: 'all_enemies',
          amount: { base: 20, scaling_stat: 'none', scaling_ratio: 0 },
          status: null,
          duration: null,
          condition: null,
        },
      ],
      targeting: null,
      exhaust: false,
      upgraded: false,
    },
  ],
};
